import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#090d16',
  },
  backgroundLayer: {
    ...StyleSheet.absoluteFillObject,
  },
  orbTop: {
    position: 'absolute',
    top: -60,
    left: -40,
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: 'rgba(59, 130, 246, 0.14)',
  },
  orbBottom: {
    position: 'absolute',
    right: -60,
    top: 200,
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: 'rgba(139, 92, 246, 0.12)',
  },
  orbCenter: {
    position: 'absolute',
    left: -30,
    bottom: 120,
    width: 160,
    height: 160,
    borderRadius: 80,
    backgroundColor: 'rgba(59, 130, 246, 0.08)',
  },
  deviceStatusWrap: {
    height: 28,
    paddingHorizontal: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#2a2038',
    backgroundColor: '#100b17',
  },
  deviceStatusText: {
    color: '#d7c8ee',
    fontSize: 12,
    fontWeight: '700',
  },
  topBar: {
    marginHorizontal: 20,
    marginTop: 18,
    marginBottom: 10,
    paddingHorizontal: 0,
    paddingTop: 0,
    paddingBottom: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flexShrink: 1,
  },
  headerGreeting: {
    marginLeft: 12,
    flexShrink: 1,
  },
  iconBtn: {
    width: 38,
    height: 38,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.15)',
    backgroundColor: 'rgba(15,23,42,0.7)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  menuBarFrame: {
    width: 30,
    height: 28,
    position: 'relative',
    justifyContent: 'center',
  },
  menuBarLine: {
    position: 'absolute',
    left: 0,
    height: 6,
    width: 28,
    borderRadius: 100,
    backgroundColor: '#bfdbfe',
    shadowColor: 'rgba(96, 165, 250, 0.6)',
    shadowOffset: { width: 0, height: 0 },
    shadowRadius: 14,
    elevation: 3,
  },
  menuBarTop: {
    top: 0,
  },
  menuBarMiddle: {
    top: 11,
  },
  menuBarBottom: {
    top: 22,
  },
  headerAvatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    borderWidth: 1.5,
    borderColor: 'rgba(148,163,184,0.18)',
    backgroundColor: '#4f46e5',
  },
  headerAvatarFallback: {
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  headerAvatarGradientA: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#2563eb',
  },
  headerAvatarGradientB: {
    position: 'absolute',
    right: -8,
    bottom: -8,
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#7c3aed',
  },
  headerAvatarFallbackText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '800',
  },
  appTitle: {
    color: '#f8fafc',
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: -0.2,
  },
  subtitle: {
    color: 'rgba(148,163,184,0.6)',
    marginTop: 0,
    fontSize: 11,
    fontWeight: '500',
    letterSpacing: 0.3,
  },
  logoutBtn: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#7353a8',
    backgroundColor: '#251734',
  },
  logoutText: {
    color: '#ffffff',
    fontWeight: '700',
  },
  tabBar: {
    marginHorizontal: 16,
    marginTop: 2,
    flexDirection: 'row',
    backgroundColor: 'rgba(15, 23, 42, 0.72)',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.14)',
    padding: 6,
  },
  tabBtn: {
    flex: 1,
    paddingVertical: 11,
    borderRadius: 14,
    alignItems: 'center',
  },
  tabBtnActive: {
    backgroundColor: '#bfdbfe',
  },
  tabText: {
    color: 'rgba(226, 232, 240, 0.72)',
    fontWeight: '700',
    fontSize: 13,
    letterSpacing: 0.3,
  },
  tabTextActive: {
    color: '#0f172a',
    fontWeight: '800',
  },
  drawerLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 30,
  },
  drawerBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(2, 6, 23, 0.6)',
  },
  drawerBackdropTouch: {
    flex: 1,
  },
  drawerPanel: {
    position: 'absolute',
    right: 0,
    top: 0,
    bottom: 0,
    width: '78%',
    maxWidth: 290,
    backgroundColor: '#0e1525',
    borderLeftWidth: 1,
    borderLeftColor: 'rgba(148,163,184,0.12)',
    paddingTop: 0,
    paddingHorizontal: 0,
  },
  drawerHeader: {
    paddingTop: 54,
    paddingHorizontal: 24,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(148,163,184,0.08)',
  },
  drawerBrand: {
    fontSize: 22,
    fontWeight: '800',
    letterSpacing: -0.3,
  },
  drawerBrandBlue: {
    color: '#bfdbfe',
  },
  drawerBrandPurple: {
    color: '#c4b5fd',
  },
  drawerUser: {
    marginTop: 14,
    flexDirection: 'row',
    alignItems: 'center',
  },
  drawerAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#4f46e5',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  drawerAvatarImage: {
    width: 36,
    height: 36,
    borderRadius: 18,
    marginRight: 10,
  },
  drawerAvatarText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '700',
  },
  drawerUserInfo: {
    flex: 1,
  },
  drawerUserName: {
    fontSize: 13,
    fontWeight: '700',
    color: '#e2e8f0',
  },
  drawerUserEmail: {
    fontSize: 11,
    color: 'rgba(148,163,184,0.5)',
    marginTop: 2,
  },
  drawerNav: {
    flex: 1,
    paddingTop: 16,
    paddingHorizontal: 16,
  },
  drawerSectionLabel: {
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 1,
    color: 'rgba(148,163,184,0.35)',
    textTransform: 'uppercase',
    paddingHorizontal: 8,
    marginBottom: 6,
    marginTop: 16,
  },
  drawerTitle: {
    color: '#f8fafc',
    fontSize: 20,
    fontWeight: '800',
    marginBottom: 12,
    letterSpacing: 0.4,
  },
  drawerItem: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 11,
    marginBottom: 2,
  },
  drawerItemActive: {
    backgroundColor: 'rgba(191, 219, 254, 0.14)',
    borderColor: 'rgba(96, 165, 250, 0.38)',
    borderWidth: 1,
  },
  drawerItemDanger: {
    backgroundColor: 'transparent',
  },
  drawerItemText: {
    color: 'rgba(148,163,184,0.7)',
    fontWeight: '600',
    fontSize: 14,
    marginLeft: 12,
  },
  drawerItemTextActive: {
    color: '#93c5fd',
  },
  drawerItemTextDanger: {
    color: 'rgba(248,113,113,0.8)',
  },
  drawerItemDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#22c55e',
    marginLeft: 'auto',
  },
  drawerDivider: {
    height: 1,
    backgroundColor: 'rgba(148, 163, 184, 0.12)',
    marginVertical: 12,
  },
  drawerFooter: {
    paddingTop: 16,
    paddingHorizontal: 16,
    paddingBottom: 24,
    borderTopWidth: 1,
    borderTopColor: 'rgba(148,163,184,0.08)',
  },
  loaderWrap: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  notesSearchOuter: {
    marginHorizontal: 20,
    marginBottom: 20,
    flexDirection: 'row',
    alignItems: 'center',
  },
  notesSearchBar: {
    minHeight: 38,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.15)',
    backgroundColor: 'rgba(15,23,42,0.9)',
    paddingHorizontal: 10,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  notesSearchIconBtn: {
    width: 17,
    height: 17,
    alignItems: 'center',
    justifyContent: 'center',
  },
  notesSearchIcon: {
    width: 17,
    height: 17,
    alignItems: 'center',
    justifyContent: 'center',
  },
  notesSearchIconCircle: {
    width: 11,
    height: 11,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.65)',
  },
  notesSearchIconHandle: {
    position: 'absolute',
    bottom: 1,
    right: 1,
    width: 5,
    height: 1.8,
    backgroundColor: 'rgba(148,163,184,0.65)',
    borderRadius: 1,
    transform: [{ rotate: '45deg' }, { translateX: 1 }],
  },
  notesSearchPlaceholder: {
    marginLeft: 8,
    fontSize: 14,
    fontWeight: '500',
    color: 'rgba(148,163,184,0.4)',
  },
  notesSectionLabel: {
    marginHorizontal: 20,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  notesSectionTitle: {
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 1,
    color: 'rgba(148,163,184,0.5)',
  },
  notesSectionCount: {
    fontSize: 11,
    color: 'rgba(96,165,250,0.6)',
    fontWeight: '600',
    letterSpacing: 0.3,
  },
  calendarToggleWrap: {
    flexDirection: 'row',
    alignSelf: 'center',
    backgroundColor: 'rgba(15,23,42,0.82)',
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.12)',
    borderRadius: 16,
    padding: 4,
    marginTop: 6,
    marginBottom: 10,
  },
  calendarToggleBtn: {
    minWidth: 78,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  calendarToggleBtnActive: {
    backgroundColor: 'rgba(37,99,235,0.22)',
  },
  calendarToggleText: {
    color: 'rgba(148,163,184,0.72)',
    fontSize: 12,
    fontWeight: '800',
  },
  calendarToggleTextActive: {
    color: '#dbeafe',
  },
  notesGrid: {
    paddingHorizontal: 20,
    paddingBottom: 122,
  },
  notesGridRow: {
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  noteCardColumn: {
    width: '48.3%',
  },
  notesEmptyState: {
    paddingTop: 24,
  },
  cardsGrid: {
    paddingHorizontal: 16,
    paddingTop: 4,
    paddingBottom: 110,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  cardColumn: {
    width: '48.5%',
    marginBottom: 14,
  },
  todoBoardWrap: {
    paddingHorizontal: 16,
    paddingTop: 4,
    paddingBottom: 34,
  },
  todoScreenWrap: {
    flex: 1,
  },
  todoModernWrap: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 34,
  },
  todoModernTitleRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  todoModernTitle: {
    color: '#f1f5f9',
    fontSize: 28,
    fontWeight: '800',
    letterSpacing: -0.5,
  },
  todoModernBadge: {
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderWidth: 1,
    borderColor: 'rgba(59,130,246,0.3)',
    backgroundColor: 'rgba(59,130,246,0.18)',
    marginBottom: 3,
  },
  todoModernBadgeText: {
    color: '#60a5fa',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  todoModernStatsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  todoModernStatCard: {
    width: '31.5%',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.11)',
    backgroundColor: 'rgba(15,23,42,0.75)',
    overflow: 'hidden',
  },
  todoModernStatCardActive: {
    borderColor: 'rgba(148,163,184,0.22)',
  },
  todoModernStatCardBlue: {},
  todoModernStatCardGreen: {},
  todoModernStatCardAmber: {},
  todoModernStatValue: {
    fontSize: 20,
    fontWeight: '800',
    letterSpacing: -0.5,
    marginBottom: 3,
  },
  todoModernStatValueBlue: {
    color: '#60a5fa',
  },
  todoModernStatValueGreen: {
    color: '#34d399',
  },
  todoModernStatValueAmber: {
    color: '#fbbf24',
  },
  todoModernStatLabel: {
    fontSize: 10,
    fontWeight: '600',
    color: 'rgba(148,163,184,0.45)',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  todoModernSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  todoModernSectionTitle: {
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 1,
    color: 'rgba(148,163,184,0.5)',
    textTransform: 'uppercase',
  },
  todoModernSectionCount: {
    fontSize: 11,
    color: 'rgba(96,165,250,0.6)',
    fontWeight: '600',
  },
  todoModernProjectsScroll: {
    paddingBottom: 8,
    paddingRight: 20,
  },
  todoModernProjectCard: {
    width: 160,
    borderRadius: 20,
    padding: 16,
    marginRight: 12,
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.12)',
    backgroundColor: 'rgba(15,23,42,0.8)',
    overflow: 'hidden',
  },
  todoModernProjectAccent: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: 3,
    height: '100%',
  },
  todoModernProjectAccentblue: {
    backgroundColor: '#3b82f6',
  },
  todoModernProjectAccentpurple: {
    backgroundColor: '#8b5cf6',
  },
  todoModernProjectAccentteal: {
    backgroundColor: '#14b8a6',
  },
  todoModernProjectAccentrose: {
    backgroundColor: '#f43f5e',
  },
  todoModernProjectAccentamber: {
    backgroundColor: '#f59e0b',
  },
  todoModernProjectTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  todoModernProjectIcon: {
    width: 32,
    height: 32,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  todoModernProjectIconblue: {
    backgroundColor: 'rgba(59,130,246,0.15)',
  },
  todoModernProjectIconpurple: {
    backgroundColor: 'rgba(139,92,246,0.15)',
  },
  todoModernProjectIconteal: {
    backgroundColor: 'rgba(20,184,166,0.15)',
  },
  todoModernProjectIconrose: {
    backgroundColor: 'rgba(244,63,94,0.15)',
  },
  todoModernProjectIconamber: {
    backgroundColor: 'rgba(245,158,11,0.15)',
  },
  todoModernProjectDelete: {
    width: 22,
    height: 22,
    borderRadius: 8,
    backgroundColor: 'rgba(148,163,184,0.08)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  todoModernProjectName: {
    fontSize: 13,
    fontWeight: '700',
    color: '#e2e8f0',
    marginBottom: 4,
  },
  todoModernProjectMeta: {
    fontSize: 11,
    color: 'rgba(148,163,184,0.45)',
    fontWeight: '500',
    marginBottom: 12,
  },
  todoModernProjectProgressTrack: {
    height: 3,
    borderRadius: 2,
    backgroundColor: 'rgba(148,163,184,0.12)',
    overflow: 'hidden',
  },
  todoModernProjectProgressFill: {
    height: '100%',
    borderRadius: 2,
  },
  todoModernProjectProgressFillblue: {
    backgroundColor: '#60a5fa',
  },
  todoModernProjectProgressFillpurple: {
    backgroundColor: '#a78bfa',
  },
  todoModernProjectProgressFillteal: {
    backgroundColor: '#34d399',
  },
  todoModernProjectProgressFillrose: {
    backgroundColor: '#fb7185',
  },
  todoModernProjectProgressFillamber: {
    backgroundColor: '#fbbf24',
  },
  todoModernProjectBottom: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
  },
  todoModernProjectPct: {
    fontSize: 10,
    fontWeight: '700',
    color: 'rgba(148,163,184,0.4)',
  },
  todoModernTaskRow: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.10)',
    backgroundColor: 'rgba(15,23,42,0.75)',
    paddingHorizontal: 14,
    paddingVertical: 13,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 9,
    overflow: 'hidden',
  },
  todoModernCheckbox: {
    width: 22,
    height: 22,
    borderRadius: 7,
    borderWidth: 1.5,
    borderColor: 'rgba(148,163,184,0.3)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  todoModernCheckboxDone: {
    backgroundColor: '#2563eb',
    borderColor: 'transparent',
  },
  todoModernTaskBody: {
    flex: 1,
    minWidth: 0,
  },
  todoModernTaskName: {
    fontSize: 13.5,
    fontWeight: '600',
    color: '#e2e8f0',
    marginBottom: 4,
  },
  todoModernTaskNameDone: {
    color: 'rgba(148,163,184,0.35)',
    textDecorationLine: 'line-through',
  },
  todoModernTaskMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  todoModernTaskTag: {
    borderRadius: 20,
    paddingHorizontal: 7,
    paddingVertical: 2,
    marginRight: 8,
    marginBottom: 2,
  },
  todoModernTaskTagblue: {
    backgroundColor: 'rgba(59,130,246,0.15)',
  },
  todoModernTaskTagpurple: {
    backgroundColor: 'rgba(139,92,246,0.15)',
  },
  todoModernTaskTagteal: {
    backgroundColor: 'rgba(20,184,166,0.15)',
  },
  todoModernTaskTagrose: {
    backgroundColor: 'rgba(244,63,94,0.15)',
  },
  todoModernTaskTagamber: {
    backgroundColor: 'rgba(245,158,11,0.15)',
  },
  todoModernTaskTagText: {
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  todoModernTaskTagTextblue: {
    color: '#60a5fa',
  },
  todoModernTaskTagTextpurple: {
    color: '#a78bfa',
  },
  todoModernTaskTagTextteal: {
    color: '#34d399',
  },
  todoModernTaskTagTextrose: {
    color: '#fb7185',
  },
  todoModernTaskTagTextamber: {
    color: '#fbbf24',
  },
  todoModernTaskDateWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 2,
  },
  todoModernTaskDateText: {
    fontSize: 10.5,
    color: 'rgba(148,163,184,0.4)',
    fontWeight: '500',
    marginLeft: 4,
  },
  todoModernTaskDateTextOverdue: {
    color: 'rgba(248,113,113,0.7)',
  },
  todoModernTaskActions: {
    marginLeft: 10,
  },
  todoModernTaskDelete: {
    width: 28,
    height: 28,
    borderRadius: 9,
    backgroundColor: 'rgba(148,163,184,0.07)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  todoBoardWrapWithFab: {
    paddingBottom: 120,
  },
  todoBoardCard: {
    backgroundColor: 'rgba(15, 23, 42, 0.72)',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.14)',
    paddingHorizontal: 18,
    paddingTop: 20,
    paddingBottom: 16,
    shadowColor: '#020617',
    shadowOpacity: 0.4,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 14 },
    elevation: 10,
  },
  todoOverviewTitle: {
    color: '#f8fafc',
    fontSize: 30,
    fontWeight: '800',
    marginBottom: 16,
    letterSpacing: 0.4,
  },
  todoFilterDropdownWrap: {
    marginBottom: 14,
  },
  todoFilterDropdownHead: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.16)',
    backgroundColor: 'rgba(15, 23, 42, 0.72)',
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  todoFilterDropdownHeadText: {
    color: '#e2e8f0',
    fontSize: 14,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  todoFilterDropdownChevron: {
    color: '#bfdbfe',
    fontSize: 12,
    fontWeight: '700',
  },
  todoFilterDropdownMenu: {
    marginTop: 6,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#4e3d69',
    backgroundColor: '#1c142b',
    overflow: 'hidden',
  },
  todoFilterDropdownItem: {
    borderTopWidth: 1,
    borderTopColor: '#3f3157',
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  todoFilterDropdownItemActive: {
    backgroundColor: '#2f2144',
  },
  todoFilterDropdownItemText: {
    color: '#e8ddfb',
    fontSize: 13,
    fontWeight: '600',
  },
  todoStatsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  todoStatCard: {
    width: '48.4%',
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.14)',
    backgroundColor: 'rgba(15, 23, 42, 0.62)',
  },
  todoStatCardActive: {
    borderColor: 'rgba(96, 165, 250, 0.4)',
    backgroundColor: 'rgba(30, 41, 80, 0.7)',
  },
  todoStatTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  todoStatValue: {
    color: '#f8fafc',
    fontSize: 30,
    fontWeight: '700',
    lineHeight: 34,
  },
  todoStatWave: {
    fontSize: 18,
    fontWeight: '700',
    opacity: 0.6,
  },
  todoStatLabel: {
    color: 'rgba(226, 232, 240, 0.68)',
    fontSize: 14,
    fontWeight: '600',
  },
  todoProjectsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
    marginTop: 4,
  },
  todoProjectsTitle: {
    color: '#f3eeff',
    fontSize: 34,
    fontWeight: '700',
  },
  todoFilterPill: {
    borderRadius: 11,
    borderWidth: 1,
    borderColor: '#d9deea',
    backgroundColor: '#fdfdff',
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  todoFilterText: {
    color: '#43495f',
    fontSize: 12,
    fontWeight: '600',
  },
  todoTimelineCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#eceff6',
    backgroundColor: '#ffffff',
    paddingHorizontal: 12,
    paddingVertical: 11,
    marginBottom: 10,
    shadowColor: '#c6cde0',
    shadowOpacity: 0.16,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
  },
  todoDatePill: {
    alignSelf: 'flex-start',
    borderRadius: 12,
    backgroundColor: '#f6f2ff',
    borderWidth: 1,
    borderColor: '#e8dfff',
    paddingHorizontal: 9,
    paddingVertical: 4,
    marginBottom: 9,
  },
  todoDatePillText: {
    color: '#6f43d6',
    fontSize: 11,
    fontWeight: '700',
  },
  todoTimelineTitle: {
    color: '#131621',
    fontSize: 22,
    fontWeight: '700',
    marginBottom: 10,
  },
  todoTimelineMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  todoDotWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 16,
  },
  todoDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 6,
  },
  todoDotPurple: {
    backgroundColor: '#7f4dff',
  },
  todoDotGreen: {
    backgroundColor: '#27be67',
  },
  todoMetaText: {
    color: '#4a5166',
    fontSize: 13,
    fontWeight: '600',
  },
  todoActionsRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  todoActionBtn: {
    borderRadius: 12,
    backgroundColor: '#f3f6fe',
    borderWidth: 1,
    borderColor: '#e4e8f4',
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginLeft: 8,
  },
  todoActionDelete: {
    backgroundColor: '#fff1f0',
    borderColor: '#ffd8d2',
  },
  todoActionText: {
    color: '#2f3650',
    fontSize: 12,
    fontWeight: '700',
  },
  todoActionDeleteText: {
    color: '#c03f33',
  },
  todoEmptyText: {
    color: '#c9b3e6',
    fontSize: 14,
    marginBottom: 14,
  },
  taskListHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 4,
    marginBottom: 10,
  },
  projectHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 4,
    marginBottom: 10,
  },
  projectHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  projectHeaderBtn: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(96, 165, 250, 0.32)',
    backgroundColor: 'rgba(15, 23, 42, 0.74)',
    paddingHorizontal: 14,
    paddingVertical: 8,
    marginLeft: 8,
  },
  projectHeaderBtnText: {
    color: '#bfdbfe',
    fontSize: 12,
    fontWeight: '700',
  },
  projectListCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.11)',
    backgroundColor: 'rgba(15,23,42,0.75)',
    paddingHorizontal: 14,
    paddingTop: 16,
    paddingBottom: 16,
    marginBottom: 12,
    minHeight: 130,
    shadowColor: '#020617',
    shadowOpacity: 0.24,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  projectListCardActive: {
    borderColor: 'rgba(96, 165, 250, 0.38)',
    backgroundColor: 'rgba(30, 41, 80, 0.72)',
  },
  projectListTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  projectListTitle: {
    color: '#e2e8f0',
    fontSize: 13,
    fontWeight: '700',
    flex: 1,
    paddingRight: 24,
    letterSpacing: -0.1,
  },
  projectListMeta: {
    color: 'rgba(148,163,184,0.55)',
    fontSize: 11.5,
    fontWeight: '600',
    lineHeight: 18,
  },
  projectDeleteIconWrap: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: 'rgba(148,163,184,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  projectOpenedHint: {
    color: '#8de0aa',
    fontSize: 11,
    marginTop: 6,
    fontWeight: '700',
  },
  projectPreviewWrap: {
    marginTop: 4,
  },
  projectPreviewRow: {
    paddingTop: 6,
    borderTopWidth: 1,
    borderTopColor: '#493661',
    marginTop: 6,
  },
  projectPreviewText: {
    color: '#efe8ff',
    fontSize: 12,
    fontWeight: '600',
  },
  projectPreviewTime: {
    color: '#aa96cb',
    fontSize: 11,
    marginTop: 2,
  },
  projectEditBtn: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#5e4a7f',
    backgroundColor: '#2a1f3e',
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  projectEditBtnText: {
    color: '#e9dcff',
    fontSize: 11,
    fontWeight: '700',
  },
  taskListHeader: {
    color: '#f8fafc',
    fontSize: 24,
    fontWeight: '800',
  },
  taskListProjectHint: {
    color: 'rgba(226, 232, 240, 0.56)',
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 8,
  },
  taskListRow: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.14)',
    backgroundColor: 'rgba(15, 23, 42, 0.66)',
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  taskCheckbox: {
    width: 24,
    height: 24,
    borderRadius: 7,
    borderWidth: 1.5,
    borderColor: 'rgba(148, 163, 184, 0.28)',
    backgroundColor: 'rgba(15, 23, 42, 0.86)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  taskCheckboxDone: {
    borderColor: '#60a5fa',
    backgroundColor: 'rgba(59, 130, 246, 0.22)',
  },
  taskCheckboxText: {
    color: 'transparent',
    fontSize: 14,
    fontWeight: '900',
    lineHeight: 16,
  },
  taskCheckboxTextDone: {
    color: '#dcfce7',
  },
  taskListBody: {
    flex: 1,
    marginRight: 8,
  },
  taskInlineDateWrap: {
    maxWidth: 124,
    marginRight: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.18)',
    backgroundColor: 'rgba(15, 23, 42, 0.84)',
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  taskInlineDateText: {
    color: '#bfdbfe',
    fontSize: 11,
    fontWeight: '600',
  },
  projectGridWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  projectGridItem: {
    width: '48.5%',
  },
  taskListTitle: {
    color: '#f8fafc',
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 20,
  },
  projectTaskInput: {
    flex: 1,
    color: '#f8fafc',
    fontSize: 15,
    fontWeight: '600',
    marginRight: 8,
    paddingVertical: 0,
  },
  taskDateTimeLine: {
    color: '#9f8cbc',
    fontSize: 12,
    marginTop: 4,
    textDecorationLine: 'underline',
  },
  taskListMeta: {
    color: '#beaadf',
    fontSize: 12,
    marginTop: 2,
  },
  taskListTime: {
    color: '#9f8cbc',
    fontSize: 12,
    marginTop: 4,
  },
  taskDeleteIconWrap: {
    width: 26,
    height: 26,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.18)',
    backgroundColor: 'rgba(15, 23, 42, 0.84)',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  taskDeleteIcon: {
    fontSize: 12,
  },
  quickPickerBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  quickPickerModal: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.14)',
    backgroundColor: 'rgba(15, 23, 42, 0.92)',
    padding: 18,
  },
  quickPickerTitle: {
    color: '#f8fafc',
    fontSize: 22,
    fontWeight: '800',
    marginBottom: 10,
  },
  quickPickerSection: {
    color: 'rgba(226, 232, 240, 0.64)',
    fontSize: 13,
    fontWeight: '600',
    marginTop: 6,
    marginBottom: 8,
  },
  quickPickerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  quickPickerCol: {
    width: '31%',
    alignItems: 'center',
  },
  quickPickerLabel: {
    color: '#beaadf',
    fontSize: 11,
    marginBottom: 4,
  },
  quickPickerBtn: {
    width: 34,
    height: 24,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: '#6b557f',
    backgroundColor: '#2a1f3e',
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickPickerBtnText: {
    color: '#f1e8ff',
    fontSize: 14,
    fontWeight: '700',
  },
  quickPickerValueBox: {
    width: 46,
    height: 28,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#6b557f',
    backgroundColor: '#120d19',
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 4,
  },
  quickPickerValueText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '700',
  },
  quickPickerActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 6,
  },
  todoEditorHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  todoEditorHeaderIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  todoEditorHeaderTitle: {
    color: '#f8fafc',
    fontSize: 20,
    fontWeight: '800',
  },
  todoEditorScrollContent: {
    paddingBottom: 18,
  },
  todoEditorCard: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.12)',
    backgroundColor: 'rgba(15,23,42,0.78)',
    padding: 16,
    marginBottom: 14,
  },
  todoEditorItemTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  todoEditorTopRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  todoEditorRemoveBtn: {
    width: 34,
    height: 34,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(244,63,94,0.08)',
  },
  todoLargeTextInput: {
    minHeight: 132,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.16)',
    backgroundColor: 'rgba(9,13,22,0.66)',
    paddingHorizontal: 14,
    paddingVertical: 14,
    color: '#f8fafc',
    fontSize: 16,
    lineHeight: 24,
    marginBottom: 14,
  },
  todoReminderSwitch: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.14)',
    backgroundColor: 'rgba(9,13,22,0.6)',
    paddingLeft: 12,
    paddingRight: 8,
    paddingVertical: 8,
    minWidth: 132,
  },
  todoReminderSwitchActive: {
    borderColor: 'rgba(96,165,250,0.34)',
  },
  todoReminderSwitchLabel: {
    color: '#e2e8f0',
    fontSize: 13,
    fontWeight: '700',
  },
  todoReminderSwitchLabelActive: {
    color: '#f8fafc',
  },
  todoReminderTrack: {
    width: 46,
    height: 28,
    borderRadius: 999,
    backgroundColor: 'rgba(51,65,85,0.72)',
    padding: 3,
    justifyContent: 'center',
  },
  todoReminderTrackActive: {
    backgroundColor: '#2563eb',
  },
  todoReminderThumb: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#ffffff',
  },
  todoReminderThumbActive: {
    alignSelf: 'flex-end',
  },
  todoReminderCompactRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
    marginTop: 2,
  },
  todoReminderIconBtn: {
    width: '48.5%',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.14)',
    backgroundColor: 'rgba(9,13,22,0.6)',
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  todoReminderIconBtnDisabled: {
    opacity: 0.45,
  },
  todoReminderIconLabel: {
    color: '#e2e8f0',
    fontSize: 13,
    fontWeight: '600',
    marginLeft: 9,
    flex: 1,
  },
  todoReminderSummaryText: {
    color: 'rgba(191,219,254,0.9)',
    fontSize: 13,
    fontWeight: '600',
  },
  todoReminderHint: {
    color: 'rgba(148,163,184,0.62)',
    fontSize: 12,
    lineHeight: 18,
    marginTop: 6,
  },
  todoPickerOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.58)',
    justifyContent: 'flex-end',
  },
  todoPickerShell: {
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    backgroundColor: '#0f172a',
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 24,
  },
  todoPickerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  todoPickerTitle: {
    color: '#f8fafc',
    fontSize: 18,
    fontWeight: '800',
  },
  todoPickerClose: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(148,163,184,0.1)',
  },
  projectScreenHeaderTick: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 4,
  },
  projectTaskCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.10)',
    backgroundColor: 'rgba(15,23,42,0.75)',
    paddingHorizontal: 14,
    paddingVertical: 14,
    marginBottom: 10,
  },
  projectTaskCardTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  projectTaskCardTitle: {
    color: '#e2e8f0',
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 22,
  },
  projectTaskCardMeta: {
    color: 'rgba(191,219,254,0.82)',
    fontSize: 12,
    fontWeight: '600',
    marginTop: 8,
  },
  calendarModernWrap: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 120,
  },
  calendarModernCard: {
    borderRadius: 28,
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.14)',
    backgroundColor: 'rgba(15,23,42,0.82)',
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 14,
    shadowColor: '#020617',
    shadowOpacity: 0.34,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  calendarModernTopBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  calendarModernMonthChip: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 999,
    backgroundColor: 'rgba(59,130,246,0.14)',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  calendarModernMonthChipText: {
    color: '#dbeafe',
    fontSize: 14,
    fontWeight: '700',
    marginLeft: 8,
  },
  calendarModernActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  calendarModernIconBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 8,
    backgroundColor: 'rgba(15,23,42,0.92)',
  },
  calendarModernWeekRow: {
    flexDirection: 'row',
    marginBottom: 10,
  },
  calendarModernWeekText: {
    flex: 1,
    textAlign: 'center',
    color: 'rgba(148,163,184,0.72)',
    fontSize: 13,
    fontWeight: '600',
  },
  calendarModernRow: {
    flexDirection: 'row',
    marginBottom: 8,
  },
  calendarModernDayPressable: {
    flex: 1,
    alignItems: 'center',
  },
  calendarModernDayBubble: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(30,41,59,0.78)',
    position: 'relative',
  },
  calendarModernDayOutside: {
    backgroundColor: 'transparent',
  },
  calendarModernDayWeekend: {
    backgroundColor: 'rgba(37,99,235,0.12)',
  },
  calendarModernDayHasItems: {
    backgroundColor: 'rgba(30,64,175,0.22)',
  },
  calendarModernDayToday: {
    borderWidth: 1.5,
    borderColor: 'rgba(96,165,250,0.7)',
  },
  calendarModernDaySelected: {
    backgroundColor: '#2563eb',
  },
  calendarModernDayText: {
    color: '#e2e8f0',
    fontSize: 15,
    fontWeight: '700',
  },
  calendarModernDayTextOutside: {
    color: 'rgba(148,163,184,0.3)',
  },
  calendarModernDayTextToday: {
    color: '#bfdbfe',
  },
  calendarModernDayTextSelected: {
    color: '#ffffff',
  },
  calendarModernIndicators: {
    position: 'absolute',
    bottom: 3,
    flexDirection: 'row',
    alignItems: 'center',
  },
  calendarModernIndicatorDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    marginHorizontal: 1.5,
  },
  calendarModernIndicatorBlue: {
    backgroundColor: '#60a5fa',
  },
  calendarModernIndicatorGreen: {
    backgroundColor: '#22c55e',
  },
  calendarModernIndicatorSlate: {
    backgroundColor: 'rgba(148,163,184,0.82)',
  },
  calendarAgendaCard: {
    marginTop: 16,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.14)',
    backgroundColor: 'rgba(15,23,42,0.82)',
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 16,
    shadowColor: '#020617',
    shadowOpacity: 0.3,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 6,
  },
  calendarAgendaHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 14,
  },
  calendarAgendaHeaderLeft: {
    flex: 1,
  },
  calendarAgendaHeaderRight: {
    alignItems: 'flex-end',
    marginLeft: 12,
  },
  calendarAgendaEyebrow: {
    color: '#93c5fd',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.7,
  },
  calendarAgendaDateNumber: {
    color: '#f8fafc',
    fontSize: 42,
    fontWeight: '800',
    lineHeight: 46,
    marginTop: 2,
  },
  calendarAgendaDateLabel: {
    color: 'rgba(148,163,184,0.78)',
    fontSize: 14,
    fontWeight: '600',
  },
  calendarAgendaSummary: {
    color: '#e2e8f0',
    fontSize: 15,
    fontWeight: '700',
  },
  calendarAgendaSummaryMuted: {
    color: 'rgba(148,163,184,0.64)',
    fontSize: 12,
    marginTop: 4,
    fontWeight: '600',
  },
  calendarAgendaEmptyCard: {
    borderRadius: 18,
    backgroundColor: 'rgba(30,41,59,0.82)',
    paddingHorizontal: 16,
    paddingVertical: 18,
  },
  calendarAgendaEmptyTitle: {
    color: '#f8fafc',
    fontSize: 15,
    fontWeight: '800',
  },
  calendarAgendaEmptyText: {
    color: 'rgba(148,163,184,0.76)',
    fontSize: 13,
    marginTop: 6,
    lineHeight: 19,
  },
  calendarAgendaTaskCard: {
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 10,
  },
  calendarAgendaToneOpen: {
    backgroundColor: 'rgba(51,65,85,0.72)',
  },
  calendarAgendaToneTimed: {
    backgroundColor: 'rgba(30,64,175,0.28)',
  },
  calendarAgendaToneDone: {
    backgroundColor: 'rgba(20,184,166,0.18)',
  },
  calendarAgendaTaskTop: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  calendarAgendaTaskDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 8,
  },
  calendarAgendaDotOpen: {
    backgroundColor: '#94a3b8',
  },
  calendarAgendaDotTimed: {
    backgroundColor: '#60a5fa',
  },
  calendarAgendaDotDone: {
    backgroundColor: '#22c55e',
  },
  calendarAgendaTaskTime: {
    color: '#cbd5e1',
    fontSize: 12,
    fontWeight: '700',
    flex: 1,
  },
  calendarAgendaBadge: {
    borderRadius: 999,
    backgroundColor: 'rgba(15,23,42,0.44)',
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  calendarAgendaBadgeText: {
    color: '#e2e8f0',
    fontSize: 11,
    fontWeight: '700',
  },
  calendarAgendaTaskTitle: {
    color: '#f8fafc',
    fontSize: 16,
    fontWeight: '800',
    lineHeight: 22,
  },
  calendarAgendaTaskMeta: {
    color: 'rgba(148,163,184,0.76)',
    fontSize: 12,
    fontWeight: '600',
    marginTop: 6,
  },
  calendarFloatingAdd: {
    position: 'absolute',
    right: 26,
    bottom: 28,
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: '#2563eb',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(191,219,254,0.5)',
    shadowColor: '#1d4ed8',
    shadowOpacity: 0.34,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 10,
  },
  noteCard: {
    backgroundColor: 'rgba(15, 23, 42, 0.72)',
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.11)',
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingTop: 16,
    paddingBottom: 28,
    minHeight: 130,
    position: 'relative',
    overflow: 'hidden',
  },
  noteAccentStrip: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: 3,
    height: '100%',
    borderTopLeftRadius: 18,
    borderBottomLeftRadius: 18,
  },
  todoCard: {
    backgroundColor: '#0f0b16',
    borderWidth: 1,
    borderColor: '#3a2d4e',
    borderRadius: 16,
    padding: 12,
    minHeight: 140,
    position: 'relative',
  },
  deleteIconWrap: {
    position: 'absolute',
    top: 12,
    right: 12,
    width: 20,
    height: 20,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(148,163,184,0.1)',
    zIndex: 1,
  },
  deleteIcon: {
    color: '#bfdbfe',
    fontWeight: '800',
    fontSize: 12,
  },
  noteTitle: {
    color: '#f8fafc',
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 7,
    paddingLeft: 10,
    paddingRight: 24,
    letterSpacing: -0.1,
  },
  noteContent: {
    color: 'rgba(148,163,184,0.55)',
    fontSize: 11.5,
    lineHeight: 18,
    paddingLeft: 10,
  },
  noteDate: {
    position: 'absolute',
    bottom: 12,
    right: 12,
    fontSize: 10,
    color: 'rgba(148,163,184,0.3)',
    fontWeight: '500',
  },
  todoTitle: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 6,
    paddingRight: 24,
  },
  todoMeta: {
    color: '#cab8e9',
    marginBottom: 8,
    fontSize: 12,
  },
  todoPreviewItem: {
    color: '#ece2ff',
    fontSize: 12,
    marginBottom: 4,
  },
  todoPreviewDone: {
    textDecorationLine: 'line-through',
    opacity: 0.7,
  },
  calendarBoardWrap: {
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 34,
  },
  calendarBoardCard: {
    backgroundColor: '#161022',
    borderRadius: 26,
    borderWidth: 1,
    borderColor: '#3d2f53',
    paddingHorizontal: 14,
    paddingTop: 18,
    paddingBottom: 14,
    shadowColor: '#000000',
    shadowOpacity: 0.28,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  calendarTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  calendarTopDate: {
    color: '#f3eeff',
    fontSize: 20,
    fontWeight: '600',
    flex: 1,
    paddingRight: 10,
  },
  calendarArrowGroup: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  calendarChevronBtn: {
    width: 30,
    height: 30,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  calendarChevronText: {
    color: '#d8c8f0',
    fontSize: 18,
    fontWeight: '700',
  },
  calendarWeekHeaderRow: {
    flexDirection: 'row',
    marginBottom: 6,
    paddingHorizontal: 2,
  },
  calendarWeekHeaderText: {
    flex: 1,
    textAlign: 'center',
    color: '#b9a7d8',
    fontSize: 12,
    fontWeight: '500',
  },
  calendarWeekRow: {
    flexDirection: 'row',
    marginBottom: 2,
  },
  calendarDayPressable: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 3,
  },
  calendarDayCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  calendarDayOutside: {
    opacity: 0.45,
  },
  calendarDaySelected: {
    backgroundColor: '#8452ff',
  },
  calendarDayText: {
    color: '#f2ebff',
    fontSize: 17,
    fontWeight: '600',
  },
  calendarDayTextOutside: {
    color: '#86759f',
  },
  calendarDayTextSelected: {
    color: '#ffffff',
  },
  calendarTaskDot: {
    position: 'absolute',
    bottom: 2,
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#3cdb91',
  },
  calendarTaskHeaderRow: {
    marginTop: 14,
    marginBottom: 4,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  calendarTaskHeaderText: {
    color: '#ffffff',
    fontSize: 24,
    fontWeight: '700',
  },
  calendarAddBtn: {
    minWidth: 68,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#8452ff',
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOpacity: 0.35,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  calendarAddBtnText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '700',
  },
  calendarEmptyText: {
    color: '#bea9df',
    fontSize: 14,
    marginTop: 10,
    marginBottom: 6,
  },
  calendarAgendaItem: {
    borderTopWidth: 1,
    borderTopColor: '#3c2d53',
    paddingVertical: 11,
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  calendarAgendaIcon: {
    width: 24,
    alignItems: 'center',
    marginTop: 4,
  },
  calendarAgendaIconInner: {
    width: 15,
    height: 15,
    borderRadius: 7.5,
    borderWidth: 1.4,
    borderColor: '#69a2ff',
    backgroundColor: '#1b1530',
  },
  calendarAgendaBody: {
    flex: 1,
    paddingLeft: 6,
  },
  calendarAgendaType: {
    color: '#ac9bc8',
    fontSize: 12,
    fontWeight: '500',
    marginBottom: 2,
  },
  calendarAgendaTitle: {
    color: '#f6f2ff',
    fontSize: 18,
    fontWeight: '600',
    lineHeight: 24,
  },
  calendarAgendaTime: {
    color: '#b8a7d7',
    marginTop: 4,
    fontSize: 14,
    fontWeight: '500',
  },
  calendarWrap: {
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 24,
  },
  calendarHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  monthArrowBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: '#7353a8',
    backgroundColor: '#251734',
    alignItems: 'center',
    justifyContent: 'center',
  },
  monthArrowText: {
    color: '#e6d5ff',
    fontSize: 16,
    fontWeight: '700',
  },
  monthTitle: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '800',
  },
  calendarCard: {
    backgroundColor: '#0f0b16',
    borderWidth: 1,
    borderColor: '#3a2d4e',
    borderRadius: 14,
    padding: 8,
  },
  weekHeaderRow: {
    flexDirection: 'row',
    marginBottom: 6,
  },
  weekHeaderText: {
    flex: 1,
    color: '#cab8e9',
    textAlign: 'center',
    fontSize: 12,
    fontWeight: '700',
  },
  weekRow: {
    flexDirection: 'row',
    marginBottom: 4,
  },
  dayCell: {
    flex: 1,
    height: 42,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#2a2038',
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 2,
    backgroundColor: '#161124',
  },
  dayCellOutside: {
    backgroundColor: '#0f0b16',
    borderColor: '#20172d',
  },
  dayCellWithTasks: {
    backgroundColor: '#253a2c',
    borderColor: '#4dbb70',
  },
  dayCellSelected: {
    borderColor: '#d9a4ff',
    borderWidth: 2,
  },
  dayCellText: {
    color: '#f4ecff',
    fontWeight: '700',
  },
  dayCellTextOutside: {
    color: '#7f7398',
  },
  dayCellTextWithTasks: {
    color: '#d6ffe1',
  },
  tasksSection: {
    marginTop: 14,
    backgroundColor: '#0f0b16',
    borderWidth: 1,
    borderColor: '#3a2d4e',
    borderRadius: 12,
    padding: 10,
  },
  tasksSectionTitle: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '800',
    marginBottom: 8,
  },
  emptyText: {
    color: '#cab8e9',
    fontSize: 14,
  },
  calendarTaskItem: {
    flexDirection: 'row',
    paddingVertical: 8,
    borderTopWidth: 1,
    borderTopColor: '#2a2038',
  },
  calendarTimeChip: {
    minWidth: 72,
    height: 26,
    borderRadius: 13,
    backgroundColor: '#2b203d',
    borderWidth: 1,
    borderColor: '#58417f',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
    marginTop: 2,
  },
  calendarTimeText: {
    color: '#ecd8ff',
    fontSize: 11,
    fontWeight: '700',
  },
  calendarItemTextWrap: {
    flex: 1,
  },
  calendarItemText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '700',
  },
  calendarItemMeta: {
    color: '#c9b3e6',
    marginTop: 2,
    fontSize: 12,
  },
  doneText: {
    textDecorationLine: 'line-through',
    opacity: 0.7,
  },
  fab: {
    position: 'absolute',
    right: 18,
    bottom: 24,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#2563eb',
    borderWidth: 1,
    borderColor: 'rgba(191, 219, 254, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#4f46e5',
    shadowOpacity: 0.46,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 10,
  },
  fabIcon: {
    color: '#ffffff',
    fontSize: 32,
    fontWeight: '500',
    lineHeight: 34,
  },
  todoFabStack: {
    position: 'absolute',
    right: 18,
    bottom: 24,
    alignItems: 'flex-end',
  },
  todoFabOptionsWrap: {
    position: 'absolute',
    right: 0,
    bottom: 66,
    alignItems: 'flex-end',
  },
  todoFabOption: {
    marginBottom: 8,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.18)',
    backgroundColor: 'rgba(15, 23, 42, 0.92)',
    paddingHorizontal: 14,
    paddingVertical: 10,
    shadowColor: '#020617',
    shadowOpacity: 0.24,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  todoFabOptionText: {
    color: '#e2e8f0',
    fontSize: 13,
    fontWeight: '700',
  },
  todoModernFabOption: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    marginBottom: 8,
  },
  todoModernFabOptionText: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.18)',
    backgroundColor: 'rgba(15,23,42,0.95)',
    color: '#e2e8f0',
    fontSize: 12,
    fontWeight: '600',
    paddingHorizontal: 12,
    paddingVertical: 7,
    marginRight: 10,
  },
  todoModernFabOptionIcon: {
    width: 38,
    height: 38,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  todoModernFabOptionProject: {
    backgroundColor: '#6d28d9',
  },
  todoModernFabOptionTask: {
    backgroundColor: '#1d4ed8',
  },
  todoModernFabOpen: {
    transform: [{ rotate: '45deg' }],
  },
  bottomNav: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 76,
    backgroundColor: 'rgba(9,13,22,0.92)',
    borderTopWidth: 1,
    borderTopColor: 'rgba(148,163,184,0.1)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingHorizontal: 8,
    paddingBottom: 12,
    zIndex: 10,
  },
  navItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 8,
    gap: 4,
  },
  navLabel: {
    fontSize: 10,
    fontWeight: '600',
    letterSpacing: 0.2,
    color: 'rgba(148,163,184,0.4)',
  },
  navLabelActive: {
    color: '#60a5fa',
  },
  navCenterWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  navFab: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: '#5b47f6',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: -22,
    borderWidth: 2,
    borderColor: 'rgba(9,13,22,0.9)',
    shadowColor: '#312e81',
    shadowOpacity: 0.34,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 10,
  },
  navFabLabel: {
    fontSize: 10,
    fontWeight: '600',
    color: '#60a5fa',
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'flex-end',
  },
  modalBackdropCentered: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  modalCard: {
    backgroundColor: '#1b1527',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: '#3e2f54',
  },
  modalCardTall: {
    backgroundColor: '#1b1527',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: '#3e2f54',
    maxHeight: '88%',
  },
  fullScreenModalCard: {
    flex: 1,
    backgroundColor: '#090d16',
    paddingHorizontal: 16,
    paddingTop: 20,
    paddingBottom: 16,
  },
  modalTitle: {
    color: '#f8fafc',
    fontSize: 24,
    fontWeight: '800',
    marginBottom: 12,
    letterSpacing: 0.3,
  },
  titleInput: {
    backgroundColor: '#111c31',
    borderWidth: 1,
    borderColor: '#263246',
    color: '#f8fafc',
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 14,
    marginBottom: 12,
    fontSize: 15,
    fontWeight: '600',
  },
  contentInput: {
    minHeight: 130,
    backgroundColor: '#271e36',
    borderWidth: 1,
    borderColor: '#4c3c67',
    color: '#ffffff',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 10,
    textAlignVertical: 'top',
  },
  fullScreenContentInput: {
    minHeight: 130,
    backgroundColor: '#271e36',
    borderWidth: 1,
    borderColor: '#4c3c67',
    color: '#ffffff',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 10,
    textAlignVertical: 'top',
  },
  noteEditorScrollContent: {
    paddingBottom: 10,
  },
  linkPreviewLoader: {
    marginTop: 12,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.14)',
    backgroundColor: 'rgba(15, 23, 42, 0.72)',
    paddingHorizontal: 16,
    paddingVertical: 18,
    flexDirection: 'row',
    alignItems: 'center',
  },
  linkPreviewLoaderText: {
    color: 'rgba(226, 232, 240, 0.72)',
    marginLeft: 10,
    fontSize: 13,
    fontWeight: '600',
  },
  itemsScroll: {
    maxHeight: 340,
  },
  fullScreenItemsScroll: {
    flex: 1,
  },
  itemsScrollContent: {
    paddingBottom: 8,
  },
  todoItemEditorRow: {
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: '#3e2f54',
    backgroundColor: '#140f1d',
    borderRadius: 12,
    padding: 8,
    marginBottom: 8,
    alignItems: 'flex-start',
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#6e5a95',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 6,
  },
  checkboxDone: {
    backgroundColor: '#d9a4ff',
    borderColor: '#d9a4ff',
  },
  checkboxText: {
    color: '#26153a',
    fontSize: 13,
    fontWeight: '800',
  },
  todoItemInputs: {
    flex: 1,
    marginLeft: 8,
    marginRight: 8,
  },
  todoTextInput: {
    backgroundColor: '#271e36',
    borderWidth: 1,
    borderColor: '#4c3c67',
    color: '#ffffff',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 8,
    marginBottom: 6,
  },
  reminderToggle: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#6e5a95',
    backgroundColor: '#241a33',
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginBottom: 8,
  },
  reminderToggleActive: {
    borderColor: '#d9a4ff',
    backgroundColor: '#3c2857',
  },
  reminderToggleText: {
    color: '#e9dcff',
    fontSize: 12,
    fontWeight: '700',
  },
  reminderToggleTextActive: {
    color: '#ffffff',
  },
  reminderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  reminderInput: {
    width: '49%',
    backgroundColor: '#271e36',
    borderWidth: 1,
    borderColor: '#4c3c67',
    color: '#ffffff',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 8,
    fontSize: 12,
  },
  reminderPreviewCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.14)',
    backgroundColor: 'rgba(15, 23, 42, 0.66)',
    padding: 12,
    marginBottom: 6,
  },
  reminderPreviewTitle: {
    color: '#bfdbfe',
    fontSize: 11,
    fontWeight: '700',
    marginBottom: 4,
  },
  reminderPreviewText: {
    color: '#f8fafc',
    fontSize: 12,
    fontWeight: '600',
    marginTop: 1,
  },
  reminderSectionCard: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.14)',
    backgroundColor: 'rgba(15, 23, 42, 0.68)',
    padding: 14,
    marginBottom: 14,
  },
  reminderSectionTitle: {
    color: '#f6f0ff',
    fontSize: 15,
    fontWeight: '800',
    marginBottom: 8,
  },
  reminderSectionItem: {
    borderTopWidth: 1,
    borderTopColor: '#3b2e51',
    paddingTop: 8,
    marginTop: 8,
  },
  reminderSectionItemFirst: {
    borderTopWidth: 0,
    paddingTop: 0,
    marginTop: 0,
  },
  reminderSectionItemTitle: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '700',
  },
  reminderSectionItemMeta: {
    color: '#cbbbe8',
    fontSize: 12,
    marginTop: 4,
  },
  itemDeleteBtn: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#321f44',
    borderWidth: 1,
    borderColor: '#6f57a2',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 6,
  },
  itemDeleteText: {
    color: '#ffd6f8',
    fontWeight: '800',
    fontSize: 11,
  },
  rollEditorWrap: {
    marginTop: 2,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#4c3c67',
    backgroundColor: '#1b1428',
    padding: 8,
  },
  rollRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  rollNumberCol: {
    width: '32%',
    alignItems: 'center',
  },
  rollNumberLabel: {
    color: '#bba8d9',
    fontSize: 11,
    marginBottom: 4,
  },
  rollArrowBtn: {
    width: 34,
    height: 24,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: '#635180',
    backgroundColor: '#271e36',
    justifyContent: 'center',
    alignItems: 'center',
  },
  rollArrowText: {
    color: '#f0e4ff',
    fontSize: 12,
    fontWeight: '700',
  },
  rollValueBox: {
    width: 50,
    height: 28,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#635180',
    backgroundColor: '#120d19',
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 4,
  },
  rollValueText: {
    color: '#ffffff',
    fontWeight: '700',
    fontSize: 13,
  },
  rollPreviewRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 3,
    marginBottom: 6,
  },
  rollPreviewText: {
    color: '#d8c9f0',
    fontSize: 12,
    fontWeight: '600',
  },
  rollClearBtn: {
    alignSelf: 'flex-start',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#6e5a95',
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: '#241a33',
  },
  rollClearText: {
    color: '#f2eaff',
    fontSize: 12,
    fontWeight: '600',
  },
  addItemBtn: {
    alignSelf: 'flex-start',
    marginTop: 4,
    backgroundColor: '#2b203d',
    borderWidth: 1,
    borderColor: '#6e5a95',
    borderRadius: 9,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  addItemBtnText: {
    color: '#e9d9ff',
    fontWeight: '700',
  },
  profileModalHint: {
    color: '#c9b3e6',
    marginBottom: 10,
  },
  profileGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    paddingBottom: 8,
  },
  profileOptionCard: {
    width: '48.5%',
    borderRadius: 22,
    borderWidth: 1,
    borderColor: 'rgba(96,165,250,0.14)',
    backgroundColor: 'rgba(15,23,42,0.86)',
    paddingVertical: 14,
    paddingHorizontal: 10,
    marginBottom: 12,
    alignItems: 'center',
    position: 'relative',
    overflow: 'hidden',
  },
  profileOptionCardActive: {
    borderColor: 'rgba(96,165,250,0.42)',
    backgroundColor: 'rgba(30,64,175,0.24)',
  },
  profileOptionGlow: {
    position: 'absolute',
    top: -24,
    left: -12,
    width: 96,
    height: 96,
    borderRadius: 999,
    backgroundColor: 'rgba(59,130,246,0.14)',
  },
  profileOptionImage: {
    width: 90,
    height: 90,
    borderRadius: 45,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.12)',
    backgroundColor: '#111827',
  },
  profileOptionBadge: {
    position: 'absolute',
    top: 10,
    right: 10,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#2563eb',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(191,219,254,0.5)',
  },
  profileOptionText: {
    color: '#dbe7fb',
    marginTop: 10,
    fontWeight: '700',
    fontSize: 12,
    textTransform: 'capitalize',
  },
  profileOptionTextActive: {
    color: '#f8fafc',
  },
  profileDetailsCard: {
    backgroundColor: 'rgba(15,23,42,0.92)',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.14)',
    padding: 18,
    alignItems: 'center',
    minWidth: 300,
  },
  profileCloseBtn: {
    alignSelf: 'flex-end',
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.16)',
    backgroundColor: 'rgba(30,41,59,0.82)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  profileCloseText: {
    color: '#e9d9ff',
    fontWeight: '800',
    fontSize: 12,
  },
  profileHeroImage: {
    width: 148,
    height: 148,
    borderRadius: 74,
    borderWidth: 2,
    borderColor: 'rgba(96,165,250,0.32)',
    backgroundColor: '#111827',
  },
  profileName: {
    color: '#f8fafc',
    marginTop: 12,
    fontSize: 22,
    fontWeight: '800',
  },
  profileEmail: {
    color: 'rgba(148,163,184,0.76)',
    marginTop: 4,
    fontSize: 13,
  },
  editImageBtn: {
    marginTop: 12,
    borderWidth: 1,
    borderColor: 'rgba(96,165,250,0.28)',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 9,
    backgroundColor: 'rgba(37,99,235,0.16)',
    flexDirection: 'row',
    alignItems: 'center',
  },
  editImageBtnText: {
    color: '#dbeafe',
    fontWeight: '700',
    marginLeft: 8,
  },
  settingsLabel: {
    color: '#ece2ff',
    fontWeight: '700',
    marginBottom: 6,
  },
  settingsHint: {
    color: '#baa5d9',
    marginTop: 4,
    marginBottom: 10,
    fontSize: 12,
  },
  modalActions: {
    marginTop: 12,
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  secondaryBtn: {
    paddingHorizontal: 16,
    paddingVertical: 11,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.22)',
    backgroundColor: 'rgba(15, 23, 42, 0.74)',
    marginRight: 8,
  },
  secondaryBtnText: {
    color: '#e2e8f0',
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  primaryBtn: {
    paddingHorizontal: 18,
    paddingVertical: 11,
    borderRadius: 999,
    backgroundColor: '#2563eb',
    borderWidth: 1,
    borderColor: 'rgba(191, 219, 254, 0.6)',
    shadowColor: '#4f46e5',
    shadowOpacity: 0.32,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  primaryBtnText: {
    color: '#ffffff',
    fontWeight: '800',
    letterSpacing: 0.3,
  },
});
